[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
ffi = false
fs_permissions = [{ access = "read", path = "./" }]

[fuzz]
runs = 256
max_test_rejects = 65536

[invariant]
runs = 128
depth = 32
fail_on_revert = false
show_metrics = true
